class Qfs < Formula
  desc "High-performance, fault-tolerant, distributed file system and its tools"
  homepage "https://github.com/quantcast/qfs"
  url "https://github.com/quantcast/qfs.git"
  version "0.0.1"
  head "https://github.com/quantcast/qfs.git"

  bottle :unneeded

  depends_on "boost"
  depends_on "cmake" => :build
  depends_on "maven" => :build
  depends_on "openssl" => :build
  depends_on "wget"

  def install
    opoo "Building qfs. This may take some time..."
    system "make", "build", "hadoop-jars", "BUILD_TYPE=release"

    bin.install "build/release/bin/chunkscrubber"
    bin.install "build/release/bin/chunkserver"
    bin.install "build/release/bin/filelister"
    bin.install "build/release/bin/logcompactor"
    bin.install "build/release/bin/metaserver"
    bin.install "build/release/bin/qfsfsck"
    bin.install "build/release/bin/tools/cpfromqfs"
    bin.install "build/release/bin/tools/cptoqfs"
    bin.install "build/release/bin/tools/qfs"
    bin.install "build/release/bin/tools/qfsadmin"
    bin.install "build/release/bin/tools/qfscat"
    bin.install "build/release/bin/tools/qfsdataverify"
    bin.install "build/release/bin/tools/qfsfileenum"
    bin.install "build/release/bin/tools/qfshibernate"
    bin.install "build/release/bin/tools/qfsping"
    bin.install "build/release/bin/tools/qfsput"
    bin.install "build/release/bin/tools/qfsshell"
    bin.install "build/release/bin/tools/qfsstats"
    bin.install "build/release/bin/tools/qfstoggleworm"
    bin.install "build/release/bin/examples/qfssample"
    bin.install "build/release/bin/emulator/rebalanceexecutor"
    bin.install "build/release/bin/emulator/rebalanceplanner"
    bin.install "build/release/bin/emulator/replicachecker"
    bin.install "build/release/bin/devtools/checksum"
    bin.install "build/release/bin/devtools/dirtree_creator"
    bin.install "build/release/bin/devtools/dtokentest"
    bin.install "build/release/bin/devtools/httpstest"
    bin.install "build/release/bin/devtools/logger"
    bin.install "build/release/bin/devtools/rand-sfmt"
    bin.install "build/release/bin/devtools/requestparser"
    bin.install "build/release/bin/devtools/sortedhash"
    bin.install "build/release/bin/devtools/sslfiltertest"
    bin.install "build/release/bin/devtools/stlset"
    bin.install "build/release/bin/devtools/xmlscannertest"

    lib.install "build/java/hadoop-qfs/hadoop-0.23.4-qfs-master.jar"
    lib.install "build/java/hadoop-qfs/hadoop-0.23.11-qfs-master.jar"
    lib.install "build/java/hadoop-qfs/hadoop-1.0.4-qfs-master.jar"
    lib.install "build/java/hadoop-qfs/hadoop-1.1.2-qfs-master.jar"
    lib.install "build/java/hadoop-qfs/hadoop-2.5.1-qfs-master.jar"
    lib.install "build/java/qfs-access/qfs-access-master.jar"
    lib.install "build/release/lib/libgf_complete.1.dylib"
    lib.install "build/release/lib/libgf_complete.dylib"
    lib.install "build/release/lib/libJerasure.2.dylib"
    lib.install "build/release/lib/libJerasure.dylib"
    lib.install "build/release/lib/libqfs_access.dylib"
    lib.install "build/release/lib/libqfs_client.dylib"
    lib.install "build/release/lib/libqfs_common.dylib"
    lib.install "build/release/lib/libqfs_io.dylib"
    lib.install "build/release/lib/libqfs_qcdio.dylib"
    lib.install "build/release/lib/libqfs_qcrs.dylib"
    lib.install "build/release/lib/libqfsc.dylib"
    lib.install "build/release/lib/libqfskrb.dylib"
    lib.install "build/release/lib/libqfss3io.dylib"
    lib.install "build/release/lib/static/libgf_complete.a"
    lib.install "build/release/lib/static/libJerasure.a"
    lib.install "build/release/lib/static/libqfs_client.a"
    lib.install "build/release/lib/static/libqfs_common.a"
    lib.install "build/release/lib/static/libqfs_emulator.a"
    lib.install "build/release/lib/static/libqfs_io.a"
    lib.install "build/release/lib/static/libqfs_meta.a"
    lib.install "build/release/lib/static/libqfs_qcdio.a"
    lib.install "build/release/lib/static/libqfs_qcrs.a"
    lib.install "build/release/lib/static/libqfs_tools.a"
    lib.install "build/release/lib/static/libqfsc.a"
    lib.install "build/release/lib/static/libqfskrb.a"
    lib.install "build/release/lib/static/libqfss3io.a"

    include.install "build/release/include/kfs/KfsAttr.h"
    include.install "build/release/include/kfs/KfsClient.h"
    include.install "build/release/include/kfs/common/kfsdecls.h"
    include.install "build/release/include/kfs/common/kfstypes.h"
    include.install "build/release/include/kfs/c/qfs.h"
  end

  test do
    system "#{bin}/qfs"
  end
end
