.TH "cpfromqfs" "1" "" "" "QFS"
.SH "NAME"
cpfromqfs \- Copy files from QFS to a local file system or to stdout
.SH "SYNOPSIS"
.B cpfromqfs
.RI [ options ] " files" ...
.SH "DESCRIPTION"
.B cpfromqfs
Copy files from QFS to a local file system or to stdout.
.SH "OPTIONS"
Supported options: skipping holes, setting of write buffer size, start and
end offsets of source file, read ahead size, op retry count, retry delay
and retry timeouts, partial sparse file support.
.TP
.B \-?, \-\-help
Show summary of options.
