.TH "cptoqfs" "1" "" "" "QFS"
.SH "NAME"
cptoqfs \- Copy files from a local file system or stdin to QFS
.SH "SYNOPSIS"
.B cptoqfs
.RI [ options ] " files" ...
.SH "DESCRIPTION"
Copy files from a local file system or stdin to QFS.
.SH "OPTIONS"
setting replication factor, data and recovery stripe counts, stripes size,
input buffer size, QFS write buffer size, truncate/delete target files,
create exclusive mode, append mode, op retry count, retry delay and retry
timeouts.
.TP
.B \-?, \-\-help
Show summary of options.
.SH "SEE ALSO"
.B cpfromqfs(1)
.B cptoqfs(1)
