.TH "qfsfileenum" "1" "" "" "QFS"
.SH "NAME"
qfsfileenum \- Prints the sizes and locations of the chunks for the given file
.SH "SYNOPSIS"
.B qfsfileenum
.RI [ options ] " files" ...
.SH "DESCRIPTION"
Prints the sizes and locations of the chunks for the given file.
.SH "OPTIONS"
.TP
.B \-?, \-\-help
Show summary of options.
.SH "SEE ALSO"
