.TH "qfshibernate" "1" "" "" "QFS"
.SH "NAME"
qfshibernate \- Hibernates a chunk server for the given number of seconds 
.SH "SYNOPSIS"
.B qfshibernate
.RI [ options ] " files" ...
.SH "DESCRIPTION"
Hibernates a chunk server for the given number of seconds.
.SH "OPTIONS"
.TP
.B \-?, \-\-help
Show summary of options.
.SH "SEE ALSO"
