.TH "qfsstats" "1" "" "" "QFS"
.SH "NAME"
qfsstats \- Reports qfs statistics
.SH "SYNOPSIS"
.B qfsstats
.RI [ options ] " files" ...
.SH "DESCRIPTION"
Reports qfs statistics.
.SH "OPTIONS"
The \-n option is used to control the interval between reports. The RPC
stats are also reported if the \-t option is used.
.TP
.B \-?, \-\-help
Show summary of options.
.SH "SEE ALSO"
