.TH "qfsshell" "1" "" "" "QFS"
.SH "NAME"
qfsshell \- Opens a simple client shell to execute QFS commands
.SH "SYNOPSIS"
.B qfsshell
.RI [ options ] " files" ...
.SH "DESCRIPTION"
Opens a simple client shell to execute QFS commands.
.SH "OPTIONS"
By default this opens an interactive shell. One can bypss the interactive
shell and execute commands directly by using the \-q option.
.TP
.B \-?, \-\-help
Show summary of options.
.SH "SEE ALSO"
